# Generated by Django 3.1.5 on 2021-02-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchObjectiveStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dragons', models.IntegerField(default=0)),
                ('barons', models.IntegerField(default=0)),
                ('turrets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('first_blood', models.BooleanField(default=False)),
                ('gold', models.IntegerField()),
                ('minions', models.IntegerField()),
                ('position', models.CharField(choices=[('TOP', 'Top'), ('JG', 'Jungle'), ('MID', 'Mid'), ('BOT', 'Bottom'), ('SUP', 'Support')], max_length=10)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lcs.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('summoner_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('region', models.CharField(max_length=10)),
                ('tournament_name', models.CharField(max_length=200)),
                ('tournament_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bottom_for_team', to='lcs.matchplayerstats')),
                ('jungle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jungle_for_team', to='lcs.matchplayerstats')),
                ('mid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mid_for_team', to='lcs.matchplayerstats')),
                ('objective', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lcs.matchobjectivestats')),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='support_for_team', to='lcs.matchplayerstats')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lcs.team')),
                ('top', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='top_for_team', to='lcs.matchplayerstats')),
            ],
        ),
        migrations.AddField(
            model_name='matchplayerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_history', to='lcs.player'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('patch', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('game_duration', models.IntegerField()),
                ('blue_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blue_side_match', to='lcs.matchteamstats')),
                ('losing_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='match_lost', to='lcs.matchteamstats')),
                ('red_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='red_side_match', to='lcs.matchteamstats')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcs.tournament')),
                ('winning_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='match_won', to='lcs.matchteamstats')),
            ],
        ),
    ]
